"""initial schema

Revision ID: 3b1af778ba89
Revises: 
Create Date: 2026-08-28 18:01:35.089697

"""
from alembic import op
import sqlalchemy as sa
import app.storage.db


revision = '3b1af778ba89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasts',
    sa.Column('forecast_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=64), nullable=False),
    sa.Column('gas', sa.String(length=16), nullable=False),
    sa.Column('generated_at', app.storage.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('based_on_event_time', app.storage.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('physics_model_version', sa.String(length=32), nullable=False),
    sa.Column('ml_model_version', sa.String(length=32), nullable=True),
    sa.Column('model_status', sa.String(length=16), nullable=False),
    sa.Column('gru_model_version', sa.String(length=32), nullable=True),
    sa.Column('gru_status', sa.String(length=16), nullable=False),
    sa.Column('horizon_minutes', sa.Integer(), nullable=False),
    sa.Column('step_minutes', sa.Integer(), nullable=False),
    sa.Column('points_json', sa.JSON(), nullable=False),
    sa.Column('leak_probability', sa.Float(), nullable=True),
    sa.Column('leak_label', sa.String(length=32), nullable=True),
    sa.Column('calibration_version', sa.String(length=32), nullable=True),
    sa.Column('feature_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('crossings_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('forecast_id')
    )
    op.create_index(op.f('ix_forecasts_generated_at'), 'forecasts', ['generated_at'], unique=False)
    op.create_index(op.f('ix_forecasts_zone_id'), 'forecasts', ['zone_id'], unique=False)
    op.create_table('incidents',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('zone_id', sa.String(length=64), nullable=False),
    sa.Column('gas', sa.String(length=16), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('opened_at', app.storage.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.storage.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', app.storage.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', app.storage.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('dedup_key', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reason_codes_json', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.String(length=1024), nullable=False),
    sa.Column('recommended_action', sa.String(length=512), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('incident_id'),
    sa.UniqueConstraint('dedup_key', 'is_active', name='uq_active_dedup')
    )
    op.create_index(op.f('ix_incidents_dedup_key'), 'incidents', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_incidents_is_active'), 'incidents', ['is_active'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_state'), 'incidents', ['state'], unique=False)
    op.create_index(op.f('ix_incidents_updated_at'), 'incidents', ['updated_at'], unique=False)
    op.create_index(op.f('ix_incidents_zone_id'), 'incidents', ['zone_id'], unique=False)
    op.create_table('model_registry',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('artifact_path', sa.String(length=256), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('training_data_version', sa.String(length=64), nullable=True),
    sa.Column('config_version', sa.String(length=32), nullable=True),
    sa.Column('metrics_path', sa.String(length=256), nullable=True),
    sa.Column('load_status', sa.String(length=16), nullable=False),
    sa.Column('loaded_at', app.storage.db.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('sensor_readings',
    sa.Column('reading_id', sa.String(length=36), nullable=False),
    sa.Column('sensor_id', sa.String(length=64), nullable=False),
    sa.Column('zone_id', sa.String(length=64), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('gas', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('event_time', app.storage.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', app.storage.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('fault_code', sa.String(length=32), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('reading_id'),
    sa.UniqueConstraint('reading_id', name='uq_reading_id')
    )
    op.create_index(op.f('ix_sensor_readings_event_time'), 'sensor_readings', ['event_time'], unique=False)
    op.create_index(op.f('ix_sensor_readings_scenario_id'), 'sensor_readings', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_sensor_id'), 'sensor_readings', ['sensor_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_zone_id'), 'sensor_readings', ['zone_id'], unique=False)
    op.create_table('simulation_commands',
    sa.Column('command_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('command', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('expected_state_version', sa.Integer(), nullable=True),
    sa.Column('resulting_state_version', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=16), nullable=False),
    sa.Column('created_at', app.storage.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('command_id')
    )
    op.create_index(op.f('ix_simulation_commands_run_id'), 'simulation_commands', ['run_id'], unique=False)
    op.create_table('simulation_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('preset', sa.String(length=64), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('generator_version', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('event_time', app.storage.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('zone_volume_m3', sa.Float(), nullable=False),
    sa.Column('inlet_co2_ppm', sa.Float(), nullable=False),
    sa.Column('source_ppm_m3_per_h', sa.Float(), nullable=False),
    sa.Column('ventilation_m3_per_h', sa.Float(), nullable=False),
    sa.Column('last_true_ppm', sa.Float(), nullable=False),
    sa.Column('worker_x', sa.Float(), nullable=False),
    sa.Column('worker_y', sa.Float(), nullable=False),
    sa.Column('worker_helmet', sa.Boolean(), nullable=False),
    sa.Column('worker_vest', sa.Boolean(), nullable=False),
    sa.Column('overhead_zone_active', sa.Boolean(), nullable=False),
    sa.Column('camera_status', sa.String(length=16), nullable=False),
    sa.Column('sensor_fault', sa.String(length=32), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_simulation_runs_is_current'), 'simulation_runs', ['is_current'], unique=False)
    op.create_index(op.f('ix_simulation_runs_scenario_id'), 'simulation_runs', ['scenario_id'], unique=False)
    op.create_table('vision_evidence',
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('zone_id', sa.String(length=64), nullable=True),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('event_time', app.storage.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', app.storage.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('detected_class', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox_x1', sa.Float(), nullable=False),
    sa.Column('bbox_y1', sa.Float(), nullable=False),
    sa.Column('bbox_x2', sa.Float(), nullable=False),
    sa.Column('bbox_y2', sa.Float(), nullable=False),
    sa.Column('helmet_state', sa.String(length=16), nullable=False),
    sa.Column('vest_state', sa.String(length=16), nullable=False),
    sa.Column('gas_zone_membership', sa.String(length=16), nullable=False),
    sa.Column('overhead_zone_membership', sa.String(length=16), nullable=False),
    sa.Column('dwell_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_vision_evidence_camera_id'), 'vision_evidence', ['camera_id'], unique=False)
    op.create_index(op.f('ix_vision_evidence_event_time'), 'vision_evidence', ['event_time'], unique=False)
    op.create_index(op.f('ix_vision_evidence_track_id'), 'vision_evidence', ['track_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('timestamp', app.storage.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('previous_state', sa.String(length=16), nullable=True),
    sa.Column('new_state', sa.String(length=16), nullable=True),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.PrimaryKeyConstraint('sequence')
    )
    op.create_index(op.f('ix_audit_events_audit_id'), 'audit_events', ['audit_id'], unique=True)
    op.create_index(op.f('ix_audit_events_incident_id'), 'audit_events', ['incident_id'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_table('incident_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_type', sa.String(length=16), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('created_at', app.storage.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_evidence_incident_id'), 'incident_evidence', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_evidence_incident_id'), table_name='incident_evidence')
    op.drop_table('incident_evidence')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_incident_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_audit_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_vision_evidence_track_id'), table_name='vision_evidence')
    op.drop_index(op.f('ix_vision_evidence_event_time'), table_name='vision_evidence')
    op.drop_index(op.f('ix_vision_evidence_camera_id'), table_name='vision_evidence')
    op.drop_table('vision_evidence')
    op.drop_index(op.f('ix_simulation_runs_scenario_id'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_is_current'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_index(op.f('ix_simulation_commands_run_id'), table_name='simulation_commands')
    op.drop_table('simulation_commands')
    op.drop_index(op.f('ix_sensor_readings_zone_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_sensor_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_scenario_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_event_time'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_table('model_registry')
    op.drop_index(op.f('ix_incidents_zone_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_updated_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_state'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_is_active'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_dedup_key'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_forecasts_zone_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_generated_at'), table_name='forecasts')
    op.drop_table('forecasts')
    # ### end Alembic commands ###
